name: Add Rockset docs
description: Upload documents to your Rockset collections on repository pushes.
icon: arrow-up-circle
color: purple

inputs:
  file:
    required: true
    description: Path of the file with the documents to be added

  collection:
    required: true
    description: Name of the collection to be added to

  workspace:
    required: false
    description: Workspace of collection
    default: commons

on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo npm install -g @rockset/cli
      - name: Authorize access
        run: |
          rockset auth:add user ${{ secrets.ROCKSET_TOKEN }}
      - name: Add docs
        run: |
          data=$(cat ${{ $INPUT_FILE }})
          echo "{\"data\": $(data) }" > data.json
          rockset api:documents:addDocuments ${{ $INPUT_WORKSPACE }} ${{ $INPUT_COLLECTION }} --body data.json